### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by DexterSK** [KittehOrg/CardboardBox#2]
Mind updateing to 1.21 ?

**Comment by mbax** [comment]
It's a work in progress. In the mean time, a reminder that Paper (which like 95% of modern servers use) will work fine. :)

**Comment by mbax** [comment]
Resolved!

Note that the groupId and package have changed for this big internal change. Tested it out on 1.8.8 paper and Spigot 1.20.4, 1.20.6, and 1.21.
